services:
  postgres:
    image: postgres:16-alpine
    container_name: techservice-postgres
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Argentina/Buenos_Aires

    ports:
      - '${DB_PORT}:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}']
      interval: 2s
      timeout: 5s
      retries: 5

    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: techservice-pgadmin
    restart: unless-stopped

    env_file:
      - .env

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False' # útil para dev local no multiple users

    ports:
      - '${PGADMIN_PORT}:80'

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - backend

volumes:
  postgres_data:
    name: techservice_postgres_data
  pgadmin_data:
    name: techservice_pgadmin_data

networks:
  backend:
    name: techservice_network
    driver: bridge
