export enum NotificationType {
  WORK_ORDER_CREATED = 'work_order.created',
  WORK_ORDER_STATUS_CHANGED = 'work_order.status_changed',
  WORK_ORDER_TECHNICIAN_ASSIGNED = 'work_order.technician_assigned',
  TASK_CREATED = 'task.created',
  TASK_COMPLETED = 'task.completed',
  PAYMENT_CREATED = 'payment.created',
  PAYMENT_APPROVED = 'payment.approved',
  PAYMENT_REJECTED = 'payment.rejected',
  PENDING_ITEM_CREATED = 'pending_item.created',
  PENDING_ITEM_DUE_TODAY = 'pending_item.due_today',
  PENDING_ITEM_OVERDUE = 'pending_item.overdue',
  INQUIRY_CREATED = 'inquiry.created',
  INQUIRY_ASSIGNED = 'inquiry.assigned',
  INQUIRY_CONTACTED = 'inquiry.contacted',
  INQUIRY_REVIEWED = 'inquiry.reviewed',
  WORK_ORDER_NOTE_ADDED = 'work_order.note_added',
  WORK_ORDER_NOTE_UPDATED = 'work_order.note_updated',
  WORK_ORDER_NOTE_DELETED = 'work_order.note_deleted',
  WORK_ORDER_MATERIAL_ADDED = 'work_order.material_added',
}
